# Generated by Django 5.1.1 on 2024-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discos',
            name='valoracion',
            field=models.IntegerField(null=True),
        ),
    ]
